"""add document_id and embedding_status to knowledge_documents

Revision ID: a4d0bb016263
Revises: 004
Create Date: 2026-06-20 00:45:32.626646
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4d0bb016263'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('a2a_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('a2a_tasks', 'callback_received',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('a2a_tasks', 'retry_count',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('a2a_tasks', 'max_retries',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('a2a_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_checklists', 'is_issue_found',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('audit_checklists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_cl_project'), table_name='audit_checklists')
    op.drop_constraint(op.f('audit_checklists_plan_id_fkey'), 'audit_checklists', type_='foreignkey')
    op.create_foreign_key(None, 'audit_checklists', 'audit_plans', ['plan_id'], ['id'])
    op.alter_column('audit_findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_interviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_intv_project'), table_name='audit_interviews')
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_plans', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_plans', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('audit_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_plan_project'), table_name='audit_plans')
    op.alter_column('audit_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_reports', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_reports', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('audit_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_report_project'), table_name='audit_reports')
    op.alter_column('behavior_risk_analysis_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('behavior_risk_management_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_stages', 'retry_count',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_index(op.f('idx_case_stages_case'), table_name='case_stages')
    op.create_index(op.f('ix_case_stages_case_id'), 'case_stages', ['case_id'], unique=False)
    op.alter_column('cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('cases_task_id_key'), 'cases', type_='unique')
    op.drop_index(op.f('idx_cases_client'), table_name='cases')
    op.drop_index(op.f('idx_cases_current_stage'), table_name='cases')
    op.drop_index(op.f('idx_cases_risk_control_case'), table_name='cases')
    op.drop_index(op.f('idx_cases_status'), table_name='cases')
    op.create_index(op.f('ix_cases_client'), 'cases', ['client'], unique=False)
    op.create_index(op.f('ix_cases_current_stage'), 'cases', ['current_stage'], unique=False)
    op.create_index(op.f('ix_cases_risk_control_case_id'), 'cases', ['risk_control_case_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_task_id'), 'cases', ['task_id'], unique=True)
    op.alter_column('exit_audit_data_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ea_dr_project'), table_name='exit_audit_data_requests')
    op.alter_column('exit_audit_findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ea_finding_project'), table_name='exit_audit_findings')
    op.alter_column('exit_audit_plans', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exit_audit_plans', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('exit_audit_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ea_plan_project'), table_name='exit_audit_plans')
    op.alter_column('exit_audit_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exit_audit_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exit_audit_questionnaires', 'is_exit_person_confirmable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('exit_audit_questionnaires', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ea_q_project'), table_name='exit_audit_questionnaires')
    op.alter_column('exit_audit_reports', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exit_audit_reports', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('exit_audit_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ea_report_project'), table_name='exit_audit_reports')
    op.alter_column('external_sync_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('external_sync_logs', 'retry_count',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('external_sync_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('generated_documents', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('generated_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_generated_documents_case'), table_name='generated_documents')
    op.create_index(op.f('ix_generated_documents_case_id'), 'generated_documents', ['case_id'], unique=False)
    op.alter_column('human_approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_human_approvals_case'), table_name='human_approvals')
    op.create_index(op.f('ix_human_approvals_case_id'), 'human_approvals', ['case_id'], unique=False)
    op.alter_column('ic_control_matrices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ic_matrix_project'), table_name='ic_control_matrices')
    op.alter_column('ic_design_defects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ic_dd_project'), table_name='ic_design_defects')
    op.drop_constraint(op.f('ic_design_defects_matrix_id_fkey'), 'ic_design_defects', type_='foreignkey')
    op.create_foreign_key(None, 'ic_design_defects', 'ic_control_matrices', ['matrix_id'], ['id'])
    op.alter_column('ic_evaluation_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ic_evaluation_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ic_evaluation_reports', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ic_evaluation_reports', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ic_evaluation_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ic_report_project'), table_name='ic_evaluation_reports')
    op.alter_column('ic_execution_defects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ic_ed_project'), table_name='ic_execution_defects')
    op.drop_constraint(op.f('ic_execution_defects_matrix_id_fkey'), 'ic_execution_defects', type_='foreignkey')
    op.create_foreign_key(None, 'ic_execution_defects', 'ic_control_matrices', ['matrix_id'], ['id'])
    op.alter_column('ic_score_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ic_score_project'), table_name='ic_score_records')
    op.alter_column('improvement_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_imp_evid_issue'), table_name='improvement_evidence')
    op.alter_column('improvement_issues', 'is_overdue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('improvement_issues', 'overdue_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('improvement_issues', 'response_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('improvement_issues', 'direct_recovery_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('improvement_issues', 'indirect_recovery_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('improvement_issues', 'is_voided',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('improvement_issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('improvement_issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('improvement_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_imp_plan_issue'), table_name='improvement_plans')
    op.alter_column('improvement_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_imp_review_issue'), table_name='improvement_reviews')
    op.alter_column('improvement_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('improvement_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_imp_task_issue'), table_name='improvement_tasks')
    op.add_column('knowledge_documents', sa.Column('document_id', sa.String(length=36), nullable=True, comment='文档分组键：同一文件的所有 chunk 共享此 UUID，由入库服务在 Python 侧生成'))
    op.add_column('knowledge_documents', sa.Column('embedding_status', sa.String(length=20), nullable=False, server_default="none", comment='向量化状态: none / pending / done / failed'))
    op.alter_column('knowledge_documents', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('knowledge_documents', 'total_chunks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('knowledge_documents', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               comment='审核状态: pending / approved / rejected',
               existing_comment='审核状态',
               existing_nullable=False,
               existing_server_default=sa.text("'approved'::character varying"))
    op.alter_column('knowledge_documents', 'security_level',
               existing_type=sa.VARCHAR(length=20),
               comment='密级: public / internal / confidential / secret',
               existing_comment='密级',
               existing_nullable=False,
               existing_server_default=sa.text("'internal'::character varying"))
    op.alter_column('knowledge_documents', 'client',
               existing_type=sa.VARCHAR(length=20),
               comment='租户: group / ecovacs / tineco',
               existing_comment='租户',
               existing_nullable=False,
               existing_server_default=sa.text("'group'::character varying"))
    op.alter_column('knowledge_documents', 'org_id',
               existing_type=sa.VARCHAR(length=50),
               comment='组织 ID，* 表示公共',
               existing_comment='组织ID',
               existing_nullable=False,
               existing_server_default=sa.text("'*'::character varying"))
    op.alter_column('knowledge_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_kb_type'), table_name='knowledge_documents')
    op.drop_index(op.f('idx_kd_approval_status'), table_name='knowledge_documents')
    op.drop_index(op.f('idx_kd_client'), table_name='knowledge_documents')
    op.drop_index(op.f('idx_kd_content_hash'), table_name='knowledge_documents')
    op.drop_index(op.f('idx_kd_org_id'), table_name='knowledge_documents')
    op.drop_index(op.f('idx_kd_security_level'), table_name='knowledge_documents')
    op.create_index(op.f('ix_knowledge_documents_approval_status'), 'knowledge_documents', ['approval_status'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_client'), 'knowledge_documents', ['client'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_content_hash'), 'knowledge_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_document_id'), 'knowledge_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_kb_type'), 'knowledge_documents', ['kb_type'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_org_id'), 'knowledge_documents', ['org_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_security_level'), 'knowledge_documents', ['security_level'], unique=False)
    op.alter_column('risk_alerts', 'alert_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_analysis_subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_analysis_subjects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_push_records', 'push_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('risk_push_records', 'callback_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('risk_push_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_rules', 'use_external_data',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('risk_rules', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('risk_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rule_iteration_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_secret_items', 'pre_review_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trade_secret_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_secret_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_secret_management_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_secret_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ts_review_item'), table_name='trade_secret_reviews')
    op.drop_constraint(op.f('trade_secret_reviews_item_id_fkey'), 'trade_secret_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'trade_secret_reviews', 'trade_secret_items', ['item_id'], ['id'])
    op.alter_column('trade_secret_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ts_sugg_item'), table_name='trade_secret_suggestions')
    op.drop_constraint(op.f('trade_secret_suggestions_item_id_fkey'), 'trade_secret_suggestions', type_='foreignkey')
    op.create_foreign_key(None, 'trade_secret_suggestions', 'trade_secret_items', ['item_id'], ['id'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_role'), table_name='users', postgresql_where='is_active')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False, postgresql_where='is_active')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'trade_secret_suggestions', type_='foreignkey')
    op.create_foreign_key(op.f('trade_secret_suggestions_item_id_fkey'), 'trade_secret_suggestions', 'trade_secret_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_ts_sugg_item'), 'trade_secret_suggestions', ['item_id'], unique=False)
    op.alter_column('trade_secret_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'trade_secret_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('trade_secret_reviews_item_id_fkey'), 'trade_secret_reviews', 'trade_secret_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_ts_review_item'), 'trade_secret_reviews', ['item_id'], unique=False)
    op.alter_column('trade_secret_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_secret_management_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_secret_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_secret_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_secret_items', 'pre_review_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rule_iteration_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_rules', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('risk_rules', 'use_external_data',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('risk_push_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_push_records', 'callback_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('risk_push_records', 'push_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('risk_analysis_subjects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_analysis_subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_alerts', 'alert_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_knowledge_documents_security_level'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_org_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_kb_type'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_document_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_content_hash'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_client'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_approval_status'), table_name='knowledge_documents')
    op.create_index(op.f('idx_kd_security_level'), 'knowledge_documents', ['security_level'], unique=False)
    op.create_index(op.f('idx_kd_org_id'), 'knowledge_documents', ['org_id'], unique=False)
    op.create_index(op.f('idx_kd_content_hash'), 'knowledge_documents', ['content_hash'], unique=False)
    op.create_index(op.f('idx_kd_client'), 'knowledge_documents', ['client'], unique=False)
    op.create_index(op.f('idx_kd_approval_status'), 'knowledge_documents', ['approval_status'], unique=False)
    op.create_index(op.f('idx_kb_type'), 'knowledge_documents', ['kb_type'], unique=False)
    op.alter_column('knowledge_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_documents', 'org_id',
               existing_type=sa.VARCHAR(length=50),
               comment='组织ID',
               existing_comment='组织 ID，* 表示公共',
               existing_nullable=False,
               existing_server_default=sa.text("'*'::character varying"))
    op.alter_column('knowledge_documents', 'client',
               existing_type=sa.VARCHAR(length=20),
               comment='租户',
               existing_comment='租户: group / ecovacs / tineco',
               existing_nullable=False,
               existing_server_default=sa.text("'group'::character varying"))
    op.alter_column('knowledge_documents', 'security_level',
               existing_type=sa.VARCHAR(length=20),
               comment='密级',
               existing_comment='密级: public / internal / confidential / secret',
               existing_nullable=False,
               existing_server_default=sa.text("'internal'::character varying"))
    op.alter_column('knowledge_documents', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               comment='审核状态',
               existing_comment='审核状态: pending / approved / rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'approved'::character varying"))
    op.alter_column('knowledge_documents', 'total_chunks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('knowledge_documents', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('knowledge_documents', 'embedding_status')
    op.drop_column('knowledge_documents', 'document_id')
    op.create_index(op.f('idx_imp_task_issue'), 'improvement_tasks', ['issue_id'], unique=False)
    op.alter_column('improvement_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('improvement_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_imp_review_issue'), 'improvement_reviews', ['issue_id'], unique=False)
    op.alter_column('improvement_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_imp_plan_issue'), 'improvement_plans', ['issue_id'], unique=False)
    op.alter_column('improvement_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('improvement_issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('improvement_issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('improvement_issues', 'is_voided',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('improvement_issues', 'indirect_recovery_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('improvement_issues', 'direct_recovery_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('improvement_issues', 'response_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('improvement_issues', 'overdue_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('improvement_issues', 'is_overdue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('idx_imp_evid_issue'), 'improvement_evidence', ['issue_id'], unique=False)
    op.alter_column('improvement_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_ic_score_project'), 'ic_score_records', ['project_id'], unique=False)
    op.alter_column('ic_score_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'ic_execution_defects', type_='foreignkey')
    op.create_foreign_key(op.f('ic_execution_defects_matrix_id_fkey'), 'ic_execution_defects', 'ic_control_matrices', ['matrix_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_ic_ed_project'), 'ic_execution_defects', ['project_id'], unique=False)
    op.alter_column('ic_execution_defects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_ic_report_project'), 'ic_evaluation_reports', ['project_id'], unique=False)
    op.alter_column('ic_evaluation_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ic_evaluation_reports', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ic_evaluation_reports', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ic_evaluation_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ic_evaluation_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'ic_design_defects', type_='foreignkey')
    op.create_foreign_key(op.f('ic_design_defects_matrix_id_fkey'), 'ic_design_defects', 'ic_control_matrices', ['matrix_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_ic_dd_project'), 'ic_design_defects', ['project_id'], unique=False)
    op.alter_column('ic_design_defects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_ic_matrix_project'), 'ic_control_matrices', ['project_id'], unique=False)
    op.alter_column('ic_control_matrices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_human_approvals_case_id'), table_name='human_approvals')
    op.create_index(op.f('idx_human_approvals_case'), 'human_approvals', ['case_id'], unique=False)
    op.alter_column('human_approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_generated_documents_case_id'), table_name='generated_documents')
    op.create_index(op.f('idx_generated_documents_case'), 'generated_documents', ['case_id'], unique=False)
    op.alter_column('generated_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_documents', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('generated_documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('external_sync_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('external_sync_logs', 'retry_count',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('external_sync_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('idx_ea_report_project'), 'exit_audit_reports', ['project_id'], unique=False)
    op.alter_column('exit_audit_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exit_audit_reports', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('exit_audit_reports', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('idx_ea_q_project'), 'exit_audit_questionnaires', ['project_id'], unique=False)
    op.alter_column('exit_audit_questionnaires', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exit_audit_questionnaires', 'is_exit_person_confirmable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('exit_audit_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exit_audit_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_ea_plan_project'), 'exit_audit_plans', ['project_id'], unique=False)
    op.alter_column('exit_audit_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exit_audit_plans', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('exit_audit_plans', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('idx_ea_finding_project'), 'exit_audit_findings', ['project_id'], unique=False)
    op.alter_column('exit_audit_findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_ea_dr_project'), 'exit_audit_data_requests', ['project_id'], unique=False)
    op.alter_column('exit_audit_data_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cases_task_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_risk_control_case_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_current_stage'), table_name='cases')
    op.drop_index(op.f('ix_cases_client'), table_name='cases')
    op.create_index(op.f('idx_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('idx_cases_risk_control_case'), 'cases', ['risk_control_case_id'], unique=False)
    op.create_index(op.f('idx_cases_current_stage'), 'cases', ['current_stage'], unique=False)
    op.create_index(op.f('idx_cases_client'), 'cases', ['client'], unique=False)
    op.create_unique_constraint(op.f('cases_task_id_key'), 'cases', ['task_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('cases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_case_stages_case_id'), table_name='case_stages')
    op.create_index(op.f('idx_case_stages_case'), 'case_stages', ['case_id'], unique=False)
    op.alter_column('case_stages', 'retry_count',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('behavior_risk_management_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('behavior_risk_analysis_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_audit_report_project'), 'audit_reports', ['project_id'], unique=False)
    op.alter_column('audit_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_reports', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('audit_reports', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_audit_plan_project'), 'audit_plans', ['project_id'], unique=False)
    op.alter_column('audit_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_plans', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('audit_plans', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_audit_intv_project'), 'audit_interviews', ['project_id'], unique=False)
    op.alter_column('audit_interviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'audit_checklists', type_='foreignkey')
    op.create_foreign_key(op.f('audit_checklists_plan_id_fkey'), 'audit_checklists', 'audit_plans', ['plan_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_audit_cl_project'), 'audit_checklists', ['project_id'], unique=False)
    op.alter_column('audit_checklists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_checklists', 'is_issue_found',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('a2a_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('a2a_tasks', 'max_retries',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('a2a_tasks', 'retry_count',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('a2a_tasks', 'callback_received',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('a2a_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
